CREATE TABLE BOOK (
    ITEM_ID BIGINT         NOT NULL,
    NAME    NVARCHAR2(256) NOT NULL,
    PATH    NVARCHAR2(256) NOT NULL,
    CONSTRAINT BOOK_PK PRIMARY KEY (ITEM_ID),
    CONSTRAINT BOOK_FK1 FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ID)
);
