CREATE TABLE ITEM (
    ID                  BIGINT   NOT NULL AUTO_INCREMENT,
    IS_NOT_CATEGORIZED  BOOLEAN  NOT NULL,
    REGISTERED_DATETIME DATETIME NOT NULL,
    CONSTRAINT ITEM_PK PRIMARY KEY (ID)
);

CREATE TABLE IMAGE (
    ITEM_ID BIGINT         NOT NULL,
    PATH    NVARCHAR2(256) NOT NULL,
    CONSTRAINT IMAGE_PK PRIMARY KEY (ITEM_ID),
    CONSTRAINT IMAGE_FK1 FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ID)
);

CREATE TABLE TAG (
    ID   BIGINT          NOT NULL AUTO_INCREMENT,
    NAME NVARCHAR2(256)  NOT NULL,
    CONSTRAINT TAG_PK PRIMARY KEY (ID),
    CONSTRAINT TAG_UK1 UNIQUE (NAME)
);

CREATE TABLE TAG_KANA (
    ID     BIGINT         NOT NULL AUTO_INCREMENT,
    TAG_ID BIGINT         NOT NULL,
    KANA   NVARCHAR(1024) NOT NULL,
    CONSTRAINT TAG_KANA_PK PRIMARY KEY (ID),
    CONSTRAINT TAG_KANA_FK1 FOREIGN KEY (TAG_ID) REFERENCES TAG (ID)
);

CREATE TABLE ITEM_TAG (
    ITEM_ID BIGINT  NOT NULL,
    TAG_ID  BIGINT  NOT NULL,
    IS_MAIN BOOLEAN NOT NULL,
    CONSTRAINT ITEM_TAG_PK PRIMARY KEY (ITEM_ID, TAG_ID),
    CONSTRAINT ITEM_TAG_FK1 FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ID),
    CONSTRAINT ITEM_TAG_FK2 FOREIGN KEY (TAG_ID) REFERENCES TAG (ID)
);
